---
- name: Install Argo CD with Helm
  hosts: localhost
  become: true

  tasks:
    - name: Add Argo CD Helm repo
      kubernetes.core.helm_repository:
        name: sealed-secrets
        url: https://bitnami-labs.github.io/sealed-secrets

    - name: Deploy Sealed Secrets chart with values loaded from template
      kubernetes.core.helm:
        name: test
        chart_ref: sealed-secrets/sealed-secrets
        chart_version: {{ sealed_secrets_helm_chart_version }}
        values: "{{ lookup('template', 'sealed_secrets_values.yml') | from_yaml }}"