---
- name: Setup the K3s Cluster
  ansible.builtin.import_playbook: k3s.orchestration.site

- name: Install Helm
  hosts: server
  become: true
  roles:
    - role: install-helm

- name: Install Argo CD with Helm
  hosts: server
  become: false
  roles:
    - role: install-argocd
